name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
    
    - name: CheckOut
      uses: actions/checkout@v3
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Restore
      run: nuget restore DesignboticAddMaterialDesingBugLauncherNoRevit/DesignboticAddMaterialDesingBugLauncherNoRevit.csproj
    - name: Build
      run: msbuild DesignboticAddMaterialDesingBugLauncherNoRevit/DesignboticAddMaterialDesingBugLauncherNoRevit.csproj
